### ISSUE TITLE
[Fabric 1.20.1] Broken beach/ocean generation

### ISSUE THREAD

**Issue by HonzaVinCZ** [Cristelknight/Expanded-Ecosphere#101]
Ocean biomes and their surroundings seem to be broken. No idea what mod might cause incompability.

Mod list:

![image](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/29098779/543af00e-930f-49d7-9feb-18180737ab5b)

Screenshots:

![2024-07-09_19 14 33](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/29098779/8afa93f7-ddc7-4653-a0ef-521557a9ee4d)
![2024-07-09_19 14 44](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/29098779/16b12dc4-931d-401c-ad10-4dd19c0609d9)
![2024-07-09_19 14 50](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/29098779/ad5e374b-0afa-4e60-9dc9-af62194d02d2)
![2024-07-09_19 15 00](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/29098779/4b5c030c-75f6-432e-ad6a-c23ebd63cd8a)

**Comment by Nekozji** [comment]
I get this same problem with just Expanded Ecosphere plus Lithosphere. Forge, 1.20.1. Don't know whether the problem is EE or Lithosphere, just found this post when googling for a solution and thought I'd mention it :')

About 10% of seeds seem to work ok and I can't actually find a flaw with those; but the rest of the time all the terrain generates very high, around y 120 or up, and when I hit an ocean biome it looks like the above.

**Comment by Cristelknight** [comment]
#115
