### ISSUE TITLE
Where to find Andesite, Diorite and Granite?

### ISSUE THREAD

**Issue by donottype** [Cristelknight/Expanded-Ecosphere#69]
I'm playing with the Create mod and I can't find most of the vanilla stones while using this world gen mod, I especially need andesite just to get started. Is there a place I can look to find where Andesite spawns? Any information would be great on knowing where I can find it.

**Comment by cpoftea** [comment]
@donottype 

Andesite, for example, can be found at some Andesite Crags biome ([ref](https://github.com/Cristelknight999/Expanded-Ecosphere/blob/108cfbff29def20fd508a058065239599c1ad0e8/common/src/main/resources/data/wythers/worldgen/biome/andesite_crags.json#L53))

You can find more references [here](https://github.com/search?q=repo%3ACristelknight999%2FExpanded-Ecosphere+path%3Acommon%2Fsrc%2Fmain%2Fresources%2Fdata%2Fwythers%2Fworldgen%2Fbiome%2F**+diorite+andesite+granite&type=code).

The problem is I have no idea these biomes are looks like

**Comment by Cristelknight** [comment]
you can re-add those features: To fix this, just open the mod, go to data/minecraft/worldgen/placed_feature, and delete the andesite, diorite and granite features. they should spawn in the newly generated biomes then. or just craft it
