### ISSUE TITLE
[Compatibility] Ecosphere 1.20.1 Fabric Breaks/Makes Infinity Cave invisible.

### ISSUE THREAD

**Issue by Dumpling00** [Cristelknight/Expanded-Ecosphere#89]
Hello! Big big fan of worldgen and biome mods and Ecospehre is practically a dream come true.

Unfortunately though, after some extensive testing, I've narrowed it down to Ecosphere being the cause of this other mod Infinity Cave not showing up/becoming invisible.
Other Worldgen mods such as William's Overhaul, Terrestria, Traverse, Terralith, Nature's Spirit and Tectonic work fine with Inifinity Cave, but for some reason Ecosphere breaks it.

Could this be looked into it, please? Would like to know if it's an issue with Ecosphere or Infinity, In doubt, I've reported to both!

Thank you for your time and consideration.

**Comment by Cristelknight** [comment]
On the modrinth description of Infinity caves it says it’s in beta and probably incompatible with many other world gen mods. That is just how worldgen works since 1.18. you can’t easily combine different things. Or in some cases not at all.

What you could try is different loading orders using the datapack versions of the mods.
