### ISSUE TITLE
 Feature order cycle crash

### ISSUE THREAD

**Issue by cal1407** [Cristelknight/Expanded-Ecosphere#96]
Game would crash during world creation. I think its because of incompatibility issue with [Woods and Mires](https://www.curseforge.com/minecraft/mc-mods/woods-and-mires).

Crash log: https://pastebin.com/eLTfmvFR

**Comment by Cristelknight** [comment]
could you please install the cyanide mod and send the crash log again. it gives more exact info. 

also this is probably an issue of woods and mires. because i made sure all features in WWEE are in the same order as in vanilla. if the devs of woods and mires want to have it i still have it laying around somewhere

**Comment by Cristelknight** [comment]
#107
